### ISSUE TITLE
开发时与打包后样式不一致

### ISSUE THREAD

**Issue by DarkGhast** [yudaocode/yudao-ui-admin-vue2#10]
任意新建一个页面，在页面中放一个<a>标签，在run dev时显示为蓝色，build后部署显示黑色

**Comment by YunaiV** [comment]
看看是不是主题的缓存哈。

**Comment by DarkGhast** [comment]
在多个不同的浏览器、无痕模式，以及多台开发电脑中表现一致，详细表现为main.js的import '@/assets/styles/index.scss'不生效。

在任意页面放一个<a>标签，在打包后以下样式生效，表现为黑色；但是run dev表现为蓝色，在F12控制台中也没找到样式
```css
a,
a:focus,
a:hover {
  cursor: pointer;
  color: inherit;
  text-decoration: none;
}
```
